# Generated by Django 5.2.1 on 2025-05-23 18:46

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_post_author_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='exchange_program',
            field=models.CharField(choices=[('Erasmus+', 'Erasmus+'), ('DAAD', 'DAAD'), ('Fulbright', 'Fulbright'), ('MEVLANA', 'Mevlana'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag_choice',
            field=models.CharField(choices=[('academic', 'Academic Advice'), ('housing', 'Housing'), ('culture', 'Cultural Experience'), ('custom', 'Other')], max_length=20),
        ),
    ]
